# Generated by Django 6.0.6 on 2026-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_user_profile_email_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=141, max_length=255),
            preserve_default=False,
        ),
    ]
