# Generated by Django 6.0.6 on 2026-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_city',
            field=models.BooleanField(default=True),
        ),
    ]
