# Generated by Django 6.0.6 on 2026-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_city'),
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='account.profile'),
        ),
    ]
